/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to use Draco compression and correct model path.
*/

import * as THREE from 'three';
import React, { useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { DRACOLoader } from 'three-stdlib';


type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.Material>;
  animations: THREE.AnimationAction[];
};

export default function Bm13Evo(props: React.ComponentProps<'group'>) {
  // ✅ Corrected path — remove /public
  // ✅ Added Draco loader setup
  const gltf = useGLTF(
    '/models/bm-13evo-draco.glb',
    true,
    undefined,
    (loader) => {
      const dracoLoader = new DRACOLoader();
      // You can use the Google CDN, or host locally in /public/draco/
      dracoLoader.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.6/');
      loader.setDRACOLoader(dracoLoader);
    }
  ) as unknown as GLTFResult;

  useEffect(() => {
    if (!gltf?.scene) {
      console.warn('3D model scene not available');
      return;
    }

    gltf.scene.traverse((child: THREE.Object3D) => {
      if ((child as THREE.Mesh).isMesh) {
        const mesh = child as THREE.Mesh;
        mesh.castShadow = true;
        mesh.receiveShadow = true;
      }
    });

    console.log('Shadows enabled for car model');
  }, [gltf]);

  if (!gltf?.scene) {
    return null;
  }

  return <primitive object={gltf.scene} {...props} />;
}

// ✅ Preload the Draco-compressed model compressor
useGLTF.preload('/models/bm-13evo-draco.glb');
